/**
 * PDF generator for DOMINIA 1.0 tickets.
 *
 * Recreates the cyberpunk ticket design:
 *  - Vertical ticket (90 x 160 mm, ~9:16 aspect ratio).
 *  - Top: cyborg hero image with overlay text "WELCOME TO" + "LSD | La Sucursal Digital".
 *  - Middle: attendee name, "Numero de Identidad" pill, cedula.
 *  - Bottom: purple "QR DE ACCESO" bar, white QR square, "Localidad" pill, locality text, footer.
 *
 * Uses jsPDF + a pre-rendered QR PNG (data URL) generated by `qrcode`.
 *
 * The cyborg source image already contains WELCOME/LSD text from the original
 * design sample, so we cover the top of the hero with a black overlay and
 * re-draw our own overlay text cleanly on top.
 */

import { jsPDF } from 'jspdf';
import QRCode from 'qrcode';
import { promises as fs } from 'fs';
import path from 'path';
import { EVENT_CONFIG } from '@/lib/constants';

const PAGE_W = 90;
const PAGE_H = 160;

const C = {
  black: [0, 0, 0] as const,
  white: [255, 255, 255] as const,
  neonGreen: [0, 255, 136] as const,
  violet: [139, 0, 255] as const,
  pillTextBlack: [0, 0, 0] as const,
  watermark: [22, 22, 22] as const,
  mutedGray: [170, 170, 170] as const,
};

/** Draw a horizontal pill (rounded rectangle) with centered text inside. */
function drawPill(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  text: string,
  fontSize: number,
) {
  doc.setFillColor(...C.neonGreen);
  doc.roundedRect(x, y, w, h, h / 2, h / 2, 'F');
  doc.setTextColor(...C.pillTextBlack);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(fontSize);
  doc.text(text, x + w / 2, y + h / 2 + fontSize * 0.35, { align: 'center' });
}

/** Draw a horizontal solid bar with centered text inside. */
function drawBar(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  text: string,
  fontSize: number,
) {
  doc.setFillColor(...C.violet);
  doc.rect(x, y, w, h, 'F');
  doc.setTextColor(...C.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(fontSize);
  doc.text(text, x + w / 2, y + h / 2 + fontSize * 0.35, { align: 'center' });
}

/**
 * Generate a ticket PDF Buffer for one attendee.
 */
export async function generateTicketPdf(data: {
  attendee: { fullName: string; cedula: string; locality: string };
  qrPayload: string;
}): Promise<Buffer> {
  const { attendee, qrPayload } = data;

  // ---- Load cyborg hero image as PNG data URL ----
  const heroPath = path.join(process.cwd(), 'public', 'assets', 'cyborg-hero.png');
  const heroBytes = await fs.readFile(heroPath);
  const heroDataUrl = `data:image/png;base64,${heroBytes.toString('base64')}`;

  // ---- Generate QR code as PNG data URL ----
  const qrDataUrl = await QRCode.toDataURL(qrPayload, {
    margin: 1,
    width: 600,
    errorCorrectionLevel: 'M',
    color: { dark: '#000000', light: '#FFFFFF' },
  });

  // ---- Build the document ----
  const doc = new jsPDF({
    unit: 'mm',
    format: [PAGE_W, PAGE_H],
    orientation: 'portrait',
    compress: true,
  });

  // 1) Background: full black
  doc.setFillColor(...C.black);
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F');

  // 2) HEADER BAND (top of the ticket) -------------------------------
  // A solid black band holds our brand text, so it never overlaps the
  // cyborg image (the source JPEG has its own baked-in text we want to hide).
  const headerH = 14;
  doc.setFillColor(...C.black);
  doc.rect(0, 0, PAGE_W, headerH, 'F');

  // 2a) "WELCOME TO" text — top-left, white, bold
  doc.setTextColor(...C.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.text(EVENT_CONFIG.welcomeText, 4, 6);

  // 2b) Brand mark — top-right: "LSD" big + "La Sucursal Digital" small
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(EVENT_CONFIG.brandMark, PAGE_W - 4, 8, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(5);
  doc.text(EVENT_CONFIG.brandSub, PAGE_W - 4, 12, { align: 'right' });

  // 3) HERO ZONE (cyborg image below the header band) ---------------
  // The cyborg image has been pre-darkened in extract-hero-image.js so any
  // baked-in text from the source JPEG is no longer visible. We render it
  // as a moody background silhouette.
  const heroH = 38; // mm — cyborg image height
  const heroY = headerH; // 14
  doc.addImage(heroDataUrl, 'PNG', 0, heroY, PAGE_W, heroH, undefined, 'FAST');

  // 3a) Translucent black gradient overlay covering the right portion of
  // the cyborg — this is where the source JPEG still shows a faint residual
  // "LSD" mark. The overlay fades that out without erasing the cyborg.
  const gStateCtor = (doc as unknown as {
    GState: new (opts: { opacity?: number }) => unknown;
  }).GState;
  if (gStateCtor) {
    // Strong overlay on the right half (where LSD mark lives)
    const overlayRight = new gStateCtor({ opacity: 0.95 });
    (doc as unknown as { setGState: (g: unknown) => void }).setGState(overlayRight);
    doc.setFillColor(...C.black);
    doc.rect(PAGE_W * 0.55, heroY, PAGE_W * 0.45, heroH, 'F');

    // Slightly softer overlay on the rest of the cyborg to suppress any
    // other faint traces from the source JPEG.
    const overlayRest = new gStateCtor({ opacity: 0.45 });
    (doc as unknown as { setGState: (g: unknown) => void }).setGState(overlayRest);
    doc.rect(0, heroY, PAGE_W * 0.55, heroH, 'F');

    // Fade the very bottom of the hero so it blends with the data zone
    doc.setFillColor(...C.black);
    const overlayBottom = new gStateCtor({ opacity: 0.8 });
    (doc as unknown as { setGState: (g: unknown) => void }).setGState(overlayBottom);
    doc.rect(0, heroY + heroH - 6, PAGE_W, 6, 'F');

    const full = new gStateCtor({ opacity: 1 });
    (doc as unknown as { setGState: (g: unknown) => void }).setGState(full);
  }

  // 4) DATA ZONE (middle) --------------------------------------------
  const dataZoneY = headerH + heroH; // 14 + 38 = 52
  const dataZoneH = 26; // mm

  // (Watermark pattern removed — it was too prominent in test renders and
  // distracted from the cédula readability.)

  // Attendee name — large, centered, white
  doc.setTextColor(...C.white);
  doc.setFont('helvetica', 'bold');
  let nameSize = 18;
  const maxNameWidth = PAGE_W - 10;
  while (nameSize > 11 && doc.getTextWidth(attendee.fullName.toUpperCase()) > maxNameWidth) {
    nameSize -= 1;
    doc.setFontSize(nameSize);
  }
  doc.setFontSize(nameSize);
  doc.text(attendee.fullName.toUpperCase(), PAGE_W / 2, dataZoneY + 10, {
    align: 'center',
  });

  // Identity pill (green pill with "Numero de Identidad")
  const pillW = 32;
  const pillH = 4.5;
  const pillX = (PAGE_W - pillW) / 2;
  const pillY = dataZoneY + 13;
  drawPill(doc, pillX, pillY, pillW, pillH, EVENT_CONFIG.labelIdentity, 6.5);

  // Cedula — large, monospaced, centered
  doc.setTextColor(...C.white);
  doc.setFont('courier', 'bold');
  doc.setFontSize(16);
  doc.text(attendee.cedula, PAGE_W / 2, dataZoneY + 23, {
    align: 'center',
  });

  // 4) ACCESS ZONE (bottom) ------------------------------------------
  const accessY = dataZoneY + dataZoneH; // 78

  // Purple "QR DE ACCESO" bar
  const barH = 7;
  drawBar(doc, 0, accessY, PAGE_W, barH, EVENT_CONFIG.labelAccess, 8);

  // QR code in a white rounded square, centered
  const qrSize = 32;
  const qrX = (PAGE_W - qrSize) / 2;
  const qrY = accessY + barH + 3; // 88

  doc.setFillColor(...C.white);
  doc.roundedRect(qrX - 2, qrY - 2, qrSize + 4, qrSize + 4, 3, 3, 'F');
  doc.addImage(qrDataUrl, 'PNG', qrX, qrY, qrSize, qrSize, undefined, 'FAST');

  // Locality pill
  const locPillY = qrY + qrSize + 3; // 88 + 32 + 3 = 123
  const locPillW = 22;
  const locPillH = 4.5;
  const locPillX = (PAGE_W - locPillW) / 2;
  drawPill(doc, locPillX, locPillY, locPillW, locPillH, EVENT_CONFIG.labelLocality, 6.5);

  // Locality value — large, elegant
  const locText = attendee.locality.toUpperCase();
  doc.setTextColor(...C.white);
  doc.setFont('helvetica', 'bold');
  let locSize = 18;
  if (locText.length > 6) locSize = 12;
  if (locText.length > 12) locSize = 10;
  doc.setFontSize(locSize);
  doc.text(locText, PAGE_W / 2, locPillY + locPillH + 8, {
    align: 'center',
  });

  // 5) FOOTER --------------------------------------------------------
  const footerY = PAGE_H - 4; // 156
  doc.setTextColor(...C.mutedGray);
  doc.setFont('courier', 'normal');
  doc.setFontSize(7);
  doc.text(EVENT_CONFIG.footer, PAGE_W / 2, footerY, { align: 'center' });

  return Buffer.from(doc.output('arraybuffer'));
}
