/**
 * PDF generator for DOMINIA 1.0 tickets.
 *
 * Recreates the cyberpunk ticket design:
 *  - Vertical ticket (90 x 160 mm, ~9:16 aspect ratio).
 *  - Top: full-width banner image (public/assets/ticket-banner.jpg) with the
 *    "WELCOME TO" + "LSD | La Sucursal Digital" branding already baked in.
 *  - Middle: attendee name, "Numero de Identidad" pill, cedula.
 *  - Bottom: purple "QR DE ACCESO" bar, white QR square, "Localidad" pill, locality text, footer.
 *
 * Uses jsPDF + a pre-rendered QR PNG (data URL) generated by `qrcode`.
 */

import { jsPDF } from 'jspdf';
import QRCode from 'qrcode';
import { promises as fs } from 'fs';
import path from 'path';
import { EVENT_CONFIG } from '@/lib/constants';

const PAGE_W = 90;
const PAGE_H = 160;

// public/assets/ticket-banner.jpg is 1600x899px; used to derive its
// on-page height from the fixed page width without distorting it.
const BANNER_ASPECT_RATIO = 1600 / 899;

// jsPDF's `fontSize` is in points but every other measurement here (x, y,
// w, h) is in mm — the vertical-centering offset below needs both in the
// same unit before applying the baseline-vs-center ratio (~1/3 of the
// font's cap height sits below the visual center of a text block).
const PT_TO_MM = 0.3528;

const C = {
  black: [0, 0, 0] as const,
  white: [255, 255, 255] as const,
  neonGreen: [0, 255, 136] as const,
  violet: [139, 0, 255] as const,
  pillTextBlack: [0, 0, 0] as const,
  watermark: [22, 22, 22] as const,
  mutedGray: [170, 170, 170] as const,
};

/** Draw a horizontal pill (rounded rectangle) with centered text inside. */
function drawPill(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  text: string,
  fontSize: number,
) {
  doc.setFillColor(...C.neonGreen);
  doc.roundedRect(x, y, w, h, h / 2, h / 2, 'F');
  doc.setTextColor(...C.pillTextBlack);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(fontSize);
  doc.text(text, x + w / 2, y + h / 2 + (fontSize * PT_TO_MM) / 3, { align: 'center' });
}

/** Draw a horizontal solid bar with centered text inside. */
function drawBar(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  text: string,
  fontSize: number,
) {
  doc.setFillColor(...C.violet);
  doc.rect(x, y, w, h, 'F');
  doc.setTextColor(...C.white);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(fontSize);
  doc.text(text, x + w / 2, y + h / 2 + (fontSize * PT_TO_MM) / 3, { align: 'center' });
}

/**
 * Generate a ticket PDF for one attendee.
 */
export async function generateTicketPdf(data: {
  attendee: { fullName: string; cedula: string; locality: string };
  qrPayload: string;
}): Promise<ArrayBuffer> {
  const { attendee, qrPayload } = data;

  // ---- Load the banner image as a JPEG data URL ----
  const bannerPath = path.join(process.cwd(), 'public', 'assets', 'ticket-banner.jpg');
  const bannerBytes = await fs.readFile(bannerPath);
  const bannerDataUrl = `data:image/jpeg;base64,${bannerBytes.toString('base64')}`;

  // ---- Generate QR code as PNG data URL ----
  const qrDataUrl = await QRCode.toDataURL(qrPayload, {
    margin: 1,
    width: 600,
    errorCorrectionLevel: 'M',
    color: { dark: '#000000', light: '#FFFFFF' },
  });

  // ---- Build the document ----
  const doc = new jsPDF({
    unit: 'mm',
    format: [PAGE_W, PAGE_H],
    orientation: 'portrait',
    compress: true,
  });

  // 1) Background: full black
  doc.setFillColor(...C.black);
  doc.rect(0, 0, PAGE_W, PAGE_H, 'F');

  // 2) BANNER (top of the ticket) --------------------------------------
  // Full-width banner with "WELCOME TO" + "LSD | La Sucursal Digital"
  // branding already designed into the image — no text overlay needed.
  const heroH = PAGE_W / BANNER_ASPECT_RATIO;
  doc.addImage(bannerDataUrl, 'JPEG', 0, 0, PAGE_W, heroH, undefined, 'FAST');

  // 3) DATA ZONE (middle) --------------------------------------------
  const dataZoneY = heroH;
  const dataZoneH = 26; // mm

  // (Watermark pattern removed — it was too prominent in test renders and
  // distracted from the cédula readability.)

  // Attendee name — large, centered, white
  doc.setTextColor(...C.white);
  doc.setFont('helvetica', 'bold');
  let nameSize = 18;
  const maxNameWidth = PAGE_W - 10;
  while (nameSize > 11 && doc.getTextWidth(attendee.fullName.toUpperCase()) > maxNameWidth) {
    nameSize -= 1;
    doc.setFontSize(nameSize);
  }
  doc.setFontSize(nameSize);
  doc.text(attendee.fullName.toUpperCase(), PAGE_W / 2, dataZoneY + 10, {
    align: 'center',
  });

  // Identity pill (green pill with "Numero de Identidad")
  const pillW = 32;
  const pillH = 4.5;
  const pillX = (PAGE_W - pillW) / 2;
  const pillY = dataZoneY + 13;
  drawPill(doc, pillX, pillY, pillW, pillH, EVENT_CONFIG.labelIdentity, 6.5);

  // Cedula — large, monospaced, centered
  doc.setTextColor(...C.white);
  doc.setFont('courier', 'bold');
  doc.setFontSize(16);
  doc.text(attendee.cedula, PAGE_W / 2, dataZoneY + 23, {
    align: 'center',
  });

  // 4) ACCESS ZONE (bottom) ------------------------------------------
  const accessY = dataZoneY + dataZoneH; // 78

  // Purple "QR DE ACCESO" bar
  const barH = 7;
  drawBar(doc, 0, accessY, PAGE_W, barH, EVENT_CONFIG.labelAccess, 8);

  // QR code in a white rounded square, centered
  const qrSize = 32;
  const qrX = (PAGE_W - qrSize) / 2;
  const qrY = accessY + barH + 3; // 88

  doc.setFillColor(...C.white);
  doc.roundedRect(qrX - 2, qrY - 2, qrSize + 4, qrSize + 4, 3, 3, 'F');
  doc.addImage(qrDataUrl, 'PNG', qrX, qrY, qrSize, qrSize, undefined, 'FAST');

  // Locality pill
  const locPillY = qrY + qrSize + 3; // 88 + 32 + 3 = 123
  const locPillW = 22;
  const locPillH = 4.5;
  const locPillX = (PAGE_W - locPillW) / 2;
  drawPill(doc, locPillX, locPillY, locPillW, locPillH, EVENT_CONFIG.labelLocality, 6.5);

  // Locality value — large, elegant
  const locText = attendee.locality.toUpperCase();
  doc.setTextColor(...C.white);
  doc.setFont('helvetica', 'bold');
  let locSize = 18;
  if (locText.length > 6) locSize = 12;
  if (locText.length > 12) locSize = 10;
  doc.setFontSize(locSize);
  doc.text(locText, PAGE_W / 2, locPillY + locPillH + 8, {
    align: 'center',
  });

  // 5) FOOTER --------------------------------------------------------
  const footerY = PAGE_H - 4; // 156
  doc.setTextColor(...C.mutedGray);
  doc.setFont('courier', 'normal');
  doc.setFontSize(7);
  doc.text(EVENT_CONFIG.footer, PAGE_W / 2, footerY, { align: 'center' });

  return doc.output('arraybuffer');
}
